title: ISS
description: A self-contained modular system in Python for autonomous driving.
theme: just-the-docs
# source: docs/

plugins:
  - jekyll-default-layout
  - jekyll/scholar

url: https://cas-lrj.github.io/iss-docs

scholar:
  style: apa
  source: ./_bibliography

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template